name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for DiceSimulator.

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see
      placeholder: Add support for multiple dice types (D20, D12, etc.)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions?
