name: ❓ Question
description: Ask a question about DiceSimulator
title: "[QUESTION] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question clearly
    validations:
      required: true
